我没搞懂，这个冲突是因为第一行同时被占用了吗？
test5没有出现冲突，test4出现冲突了，newfuntion的内容跟test4的内容不一致
说明合并的时候，你可以新增一个之前没有出现的功能，但是如果是已经在两个分支都有的文件下，你做出修改，合并则会发生冲突。