如果这个时候合并发生冲突，那就说明因为master的test4第一行跟newfuntion的第一行内容不同，所以导致了冲突。